# Source Generated with Decompyle++
# File: 019_EdgeDiagnosticsApp.init_sim_ui.create_plot.pyc (Python 3.12)

f = QFrame()
f.setProperty('class', 'Panel')
l = QVBoxLayout(f)
l.setContentsMargins(10, 10, 10, 10)
lbl = QLabel(title)
lbl.setProperty('class', 'Title')
l.addWidget(lbl)
p = pg.PlotWidget()
p.showGrid(x = True, y = True, alpha = 0.2)
p.setMouseEnabled(x = False, y = False)
legend = pg.LegendItem(offset = (50, 10))
legend.setParentItem(p.graphicsItem())
c1 = p.plot(pen = pg.mkPen(color1, width = 3), name = name1)
c2 = p.plot(pen = pg.mkPen(color2, width = 3), name = name2)
l.addWidget(p)
return (f, c1, c2)
